#!/bin/sh

. gconfig

ARCH=qemu$1
SUFFIX=$2

SUITE=$(echo "$2" | awk -F- '{print $1}')
A=$(echo "$2" | awk -F- '{print $2}')

IMAGE_SUFFIX=$SUFFIX.qcow2

if [ ! -e target-"${IMAGE_SUFFIX}" ]
then
    make-clean-vm --suite ${SUITE} --arch ${A}
fi

if [ -z "$USE_LXC" ]; then
    kvm -cpu $ARCH -m ${VMEM:-2000} -smp ${NPROCS:-2} -drive file=target-${IMAGE_SUFFIX} -net nic,model=virtio -net user,hostfwd=tcp:127.0.0.1:$VM_SSH_PORT-:22 -vnc 127.0.0.1:16 2>&1 | tee var/target.log &
    echo $! > var/target.pid
    wait
    rm var/target.pid
else
    true #sudo lxc-start -n gitian -c var/target.log -f lxc.config
fi
